In [48]:
#1. Basic Array Operations 
#Convert the mpg column into a NumPy array and calculate: 
#○ The mean, median, and standard deviation of mpg. 
#○ The number of cars with mpg greater than 25.

In [49]:
import numpy as np
import pandas as pd

In [50]:
df=pd.read_csv("auto-mpg.csv")
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [51]:
#convert mpg column into a NumPy array
df1=df["mpg"].values
df1

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [52]:
# calculate:The mean, median, and standard deviation of mpg
print("Mean = ",np.mean(df1))
print("Median =",np.median(df1))
print("Standard Deviation =",np.std(df1))

Mean =  23.514572864321607
Median = 23.0
Standard Deviation = 7.806159061274433


In [53]:
#The number of cars with mpg greater than 25.
boolean=df1 > 25
boolean.sum()

np.int64(158)

In [54]:
#2. Filtering 
#Using NumPy, filter all cars with more than 6 cylinders. Return the corresponding car_name as a list. 

In [55]:
cylinder_num=(df[df["cylinders"] > 6])["car name"].tolist()
cylinder_num

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

In [56]:
#3. Statistical Analysis 
#Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy. 

In [57]:
#sorted the column "Weight"
weight_arr=np.sort(df["weight"])
quartile25=np.percentile(weight_arr,25)
print("25th Percentile =",quartile25)
quartile50=np.percentile(weight_arr,50)
print("50th Percentile =",quartile50)
quartile75=np.percentile(weight_arr,75)
print("70th Percentile =",quartile75)

25th Percentile = 2223.75
50th Percentile = 2803.5
70th Percentile = 3608.0


In [58]:
#4. Array Manipulation 
#Convert the acceleration column into a NumPy array and normalize its values (scale between 0 and 1).

In [59]:
#Convert into array
acc_arr=df["acceleration"].values
#Min value
acc_min=acc_arr.min()
#Max value
acc_max=acc_arr.max()
print("Min value =",acc_min,"Max value =",acc_max)
#Range=max-min value
acc_range=acc_max-acc_min
print("Range=",acc_range)
#Normalization=(value-min)/range
acc_norm=((acc_arr-acc_min)/acc_range)
print("Normalized value =",acc_norm)

Min value = 8.0 Max value = 24.8
Range= 16.8
Normalized value = [0.23809524 0.20833333 0.17857143 0.23809524 0.14880952 0.11904762
 0.05952381 0.0297619  0.11904762 0.0297619  0.11904762 0.
 0.08928571 0.11904762 0.41666667 0.44642857 0.44642857 0.47619048
 0.38690476 0.74404762 0.56547619 0.38690476 0.56547619 0.26785714
 0.41666667 0.35714286 0.41666667 0.32738095 0.625      0.38690476
 0.44642857 0.35714286 0.6547619  0.29761905 0.44642857 0.44642857
 0.44642857 0.44642857 0.23809524 0.20833333 0.32738095 0.29761905
 0.20833333 0.23809524 0.23809524 0.32738095 0.6547619  0.41666667
 0.38690476 0.35714286 0.35714286 0.68452381 0.38690476 0.6547619
 0.5952381  0.6547619  0.74404762 0.44642857 0.53571429 0.92261905
 0.68452381 0.50595238 0.23809524 0.23809524 0.32738095 0.29761905
 0.20833333 0.17857143 0.32738095 0.32738095 0.26785714 0.32738095
 0.26785714 0.35714286 0.47619048 0.35714286 0.38690476 0.5952381
 0.68452381 0.5952381  0.47619048 0.53571429 0.38690476 0.41666667
 0.50595

In [60]:
#5. Broadcasting 
#Increase all horsepower values by 10% and store the updated values in a new NumPy array.
#Handle missing data (if any) by replacing it with the mean of the column before applying the increase. 

In [61]:
#Convert to numeric (turns '?' into NaN)
horse_arr = pd.to_numeric(df['horsepower'], errors='coerce').values
# Calculate mean horsepower (ignoring NaN)
horse_mean = np.nanmean(horse_arr)
# Replace NaN values with the mean
horse_replace = np.where(np.isnan(horse_arr), horse_mean, horse_arr)
horse_increase = horse_replace * 1.10
print(horse_increase)

[143.         181.5        165.         165.         154.
 217.8        242.         236.5        247.5        209.
 187.         176.         165.         247.5        104.5
 104.5        106.7         93.5         96.8         50.6
  95.7         99.         104.5        124.3         99.
 236.5        220.         231.         212.3         96.8
  99.         104.5        114.91632653 110.         115.5
 110.          96.8        110.         181.5        192.5
 168.3        165.         198.         187.         192.5
 121.          79.2        110.          96.8         94.6
  99.          77.          83.6         71.5         75.9
  66.          77.         104.5         88.          59.4
  99.          94.6        181.5        192.5        165.
 168.3        165.         228.8        170.5        176.
 209.         106.7        165.         143.         154.
 165.         123.2         83.6         95.7         75.9
  94.6        101.2        106.7         88.          96.8
 19

In [62]:
#6.Boolean Indexing 
#Find the average displacement of cars with an origin of 2 (Europe) using NumPy indexing. 

In [63]:
origin_arr=df.values
origin_arr1=origin_arr[:,[2,7]]
displacement_mean=np.mean(origin_arr1[:,0])
print("Average displacement =",displacement_mean)

Average displacement = 193.42587939698493


In [64]:
#7. Matrix Operations 
#Create a 2D NumPy array containing the columns mpg, horsepower, and weight. 
#Compute the dot product of this matrix with a given vector [1, 0.5, -0.2]. 

In [65]:
numpy_arr=pd.to_numeric(df['horsepower'], errors='coerce').values
weight=df["weight"].values
mpg=df["mpg"].values
stack=np.column_stack((mpg,numpy_arr,weight))
print("Numpy array",stack)
vector=np.array([1, 0.5, -0.2])
dot_pdt=np.dot(stack,vector)
print("Dot product =",dot_pdt)

Numpy array [[  18.  130. 3504.]
 [  15.  165. 3693.]
 [  18.  150. 3436.]
 ...
 [  32.   84. 2295.]
 [  28.   79. 2625.]
 [  31.   82. 2720.]]
Dot product = [-617.8 -641.1 -594.2 -595.6 -602.8 -754.2 -746.8 -740.9 -758.5 -660.
 -612.6 -627.8 -662.2 -490.7 -402.9 -497.1 -488.3 -453.9 -355.  -318.
 -465.9 -417.  -402.5 -364.3 -463.6 -805.5 -765.2 -760.4 -840.9 -355.
 -379.8 -373.1    nan -457.8 -619.3 -598.8 -597.4 -589.6 -745.3 -791.3
 -740.3 -730.2 -889.  -851.2 -927.5 -519.4 -423.6 -587.4 -565.8 -378.
 -351.6 -349.8 -345.  -291.1 -253.1 -309.8 -330.  -384.1 -360.2 -400.8
 -416.6 -381.2 -759.3 -775.5 -737.  -735.3 -642.4 -811.6 -809.9 -799.2
 -776.4 -398.5 -688.4 -741.6 -775.8 -726.4 -512.6 -442.2 -531.3 -377.3
 -414.  -383.6 -429.7 -364.8 -349.  -719.5 -645.4 -712.1 -725.9 -665.4
 -879.4 -804.8 -780.6 -758.4 -826.5 -865.7 -663.7 -553.7 -589.6 -521.
 -542.2 -510.3 -341.  -913.4 -885.7 -832.8 -797.8 -489.8 -391.8 -423.2
 -406.8 -361.8 -400.5 -419.9 -382.  -728.9 -724.6 -319.9 -370.1 -4

In [66]:
#8. Sorting 
#Use NumPy to sort the cars by model_year in descending order and display the first five car names

In [67]:
model_arr=df["model year"].to_numpy()
car_name=df["car name"].to_numpy()
sort=np.argsort(-model_arr)
print("Top 5 cars",car_name[sort[:5]])

Top 5 cars ['chevy s-10' 'ford ranger' 'dodge rampage' 'vw pickup' 'ford mustang gl']


In [68]:
#9. Correlation 
#Compute the Pearson correlation coefficient between mpg and weight using NumPy.

In [69]:
mpg = df['mpg'].values
weight = df['weight'].values
pearson_correlation = np.corrcoef(mpg, weight)
print(pearson_correlation)
pearson_corr = pearson_correlation[0,1]
print("Pearson correlation between mpg and weight ",pearson_corr)

[[ 1.         -0.83174093]
 [-0.83174093  1.        ]]
Pearson correlation between mpg and weight  -0.8317409332443354


In [70]:
#10. Conditional Aggregates 
#Calculate the mean mpg for cars grouped by the number of cylinders using NumPy techniques.

In [71]:
cylinders = df['cylinders'].to_numpy()
mpg = df['mpg'].to_numpy()
group_cylinders = np.unique(cylinders)
for i in group_cylinders:
    mean_mpg=mpg[cylinders == i].mean()
    print("MPG Mean of cylinder",i,"=",mean_mpg)

MPG Mean of cylinder 3 = 20.55
MPG Mean of cylinder 4 = 29.28676470588235
MPG Mean of cylinder 5 = 27.366666666666664
MPG Mean of cylinder 6 = 19.985714285714284
MPG Mean of cylinder 8 = 14.963106796116506


In [72]:
#1.Basic Exploration 
#Load the dataset into a Pandas DataFrame. Display: 
#○ The first 10 rows 
#○ The total number of rows and columns 
#○ Summary statistics for numerical columns 

In [73]:
df=pd.read_csv("auto-mpg.csv")
print(df.head(10))
print("Rows and Columns =",df.shape)
df.describe()

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skyla

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [74]:
#2. Filtering and Indexing 
#Find all cars manufactured in 1975 with a weight less than 3000. Return the DataFrame with selected columns: car_name, weight, and mpg. 

In [75]:
model=df[(df["model year"]==75 ) & (df["weight"] < 3000)][["car name","weight","mpg"]]
model

car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [76]:
#3. Handling Missing Data 
#Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median. 

In [77]:
df.isna().sum()
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())
print("After replaciing missing values",df.isna().sum())

After replaciing missing values mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64


In [78]:
#4. Data Transformation 
#Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [79]:
df['horsepower'] = df['horsepower'].replace('?', np.nan)
df['horsepower'] = df['horsepower'].astype(float)
df["power_to_weight_ratio"]=df["horsepower"]/df["weight"]
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  
0            70       1  chevrolet chevelle malibu               0.037100  
1            70       1          buick skylark 320               0.044679  
2            70       1         plymouth satellite               0.043655  
3            70       1              amc rebel sst               0.043694  
4            70       1                ford torino               0.040591  
..          ...     ...                        ...                    ...  
393          82       1            ford mustang gl               0.030824  
394          82       2                  vw pickup               0.024413  
395          82       1              dodge rampage               0.036601  
396          82       1                ford ranger               0.030095  
397          82       1                 chevy s-10               0.030147  

[398 rows x 10 columns]

In [80]:
#5. Group By 
#Group the cars by origin and calculate the mean mpg for each group. 

In [81]:
group=df.groupby("origin")
mean=group.mean(["mpg"])
mean[["mpg"]]

mpg
origin           
1       20.083534
2       27.891429
3       30.450633

In [82]:
#6. Sorting 
#Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg. 

In [83]:
sorted_data=df.sort_values(by='mpg', ascending=False)
sorted_data.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0        93.5    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050954  
324               0.030806  
247               0.033816

In [84]:
#7. Apply this function to each row and store the result in the new column. 
#Apply Function 
#Create a new column performance_score using a custom function: 
#def performance_score(row): 
#return row['mpg'] * row['acceleration'] / row['weight'] 

In [85]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']
df['performance_score'] = df.apply(performance_score, axis=1)
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  \
0            70       1  chevrolet chevelle malibu               0.037100   
1            70       1          buick skylark 320               0.044679   
2            70       1         plymouth satellite               0.043655   
3            70       1              amc rebel sst               0.043694   
4            70       1                ford torino               0.040591   
..          ...     ...                        ...                    ...   
393          82       1            ford mustang gl               0.030824   
394          82       2                  vw pickup               0.024413   
395          82       1              dodge rampage               0.036601   
396          82       1                ford ranger               0.030095   
397          82       1                 chevy s-10               0.030147   

     performance_score  
0             0.061644  
1             0.046710  
2             0.057625  
3             0.055928  
4             0.051754  
..                 ...  
393           0.150968  
394           0.508169  
395           0.161743  
396           0.198400  
397           0.221103  

[398 rows x 11 columns]

In [86]:
#8. Visualization Preparation 
#Generate a summary DataFrame with: 
#○ Average mpg, weight, and horsepower for each model_year.

In [87]:
model_yr=df.groupby(df["model year"])[["mpg","weight","horsepower"]].mean()
model_yr

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

In [88]:
#9. Exporting Data 
#Save a subset of the data containing only mpg, cylinders, horsepower, and weight for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [89]:
file=df[df["mpg"] > 30][["mpg","cylinders","horsepower","weight"]]
file.to_csv("high_mpg_cars.csv")
file_read=pd.read_csv("high_mpg_cars.csv")
file_read

Unnamed: 0   mpg  cylinders  horsepower  weight
0           53  31.0          4        65.0    1773
1           54  35.0          4        69.0    1613
2          129  31.0          4        67.0    1950
3          131  32.0          4        65.0    1836
4          144  31.0          4        52.0    1649
..         ...   ...        ...         ...     ...
80         390  32.0          4        96.0    2665
81         391  36.0          4        84.0    2370
82         394  44.0          4        52.0    2130
83         395  32.0          4        84.0    2295
84         397  31.0          4        82.0    2720

[85 rows x 5 columns]

In [90]:
#10. Finding Anomalies 
#Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifically: 
#● Calculate the IQR for mpg. 
#● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR. 
#● Create a DataFrame of cars classified as outliers, displaying car_name, mpg, and model_year. 

In [91]:
describe=df.describe()
Q1=describe.loc["25%","mpg"]
Q3=describe.loc["75%","mpg"]
IQR=Q3-Q1
print("IQR =",IQR)
Lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print("Lower bound =",Lower_bound,",Upper bound =",upper_bound)
outliers=df[(df["mpg"] < Lower_bound) | (df["mpg"] >   upper_bound)][["car name","mpg","model year"]]
outliers

IQR = 11.5
Lower bound = 0.25 ,Upper bound = 46.25


car name   mpg  model year
322  mazda glc  46.6          80